version: '3.8'

services:
  receiver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_BOT_KEY=${TELEGRAM_BOT_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BACKEND_ENDPOINT=http://aws.kmrasmussen.com/telegramboilerservice1/myendpoint
    volumes:
      - ./voice_messages:/app/voice_messages
      - .:/app
    command: python receiver.py